#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef PLAYTIMEMONETIZE_SWIFT_H
#define PLAYTIMEMONETIZE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PlaytimeMonetize",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class PlaytimeOptions;
/// The entry point of adjoe Playtime SDK.
/// note:
/// The SDK is functional starting from <em>iOS 14.0</em>.
SWIFT_CLASS("_TtC16PlaytimeMonetize8Playtime")
@interface Playtime : NSObject
/// Initialize Playtime SDK.
/// warning:
/// If you don’t use auto-init, you <em>must</em> call this method before any other SDK APIs or they will throw
/// <code>PlaytimeError.performingOperationBeforeSDKInitialized</code>.
/// \param userID Publisher’s user ID.
///
/// \param sdkHash SDK hash that you received from the Adjoe Monetize dashboard.
///
/// \param uaNetwork User acquisition network where the user came from.
///
/// \param uaChannel User acquisition channel where the user came from; e.g. video, offerwall.
///
/// \param uaSubPublisherCleartext User acquisition sub ID in clear text where the user came from.
///
/// \param uaSubPublisherEncrypted User acquisition sub ID in encrypted form where the user came from.
///
/// \param placement The placement of the Playtime experience; e.g. “home screen”, “more options menu”.
///
+ (void)initializeWithUserID:(NSString * _Nullable)userID sdkHash:(NSString * _Nonnull)sdkHash uaNetwork:(NSString * _Nullable)uaNetwork uaChannel:(NSString * _Nullable)uaChannel uaSubPublisherCleartext:(NSString * _Nullable)uaSubPublisherCleartext uaSubPublisherEncrypted:(NSString * _Nullable)uaSubPublisherEncrypted placement:(NSString * _Nullable)placement completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Present a screen view with the Playtime catalog.
/// \param options Options for the Playtime catalog.
///
+ (void)showCatalogWithOptions:(PlaytimeOptions * _Nullable)options completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PlaytimeEventConfig;
@class PlaytimeMedia;
@class PlaytimePromotion;
/// The model that represents a campaign and/or installed application.
SWIFT_CLASS("_TtC16PlaytimeMonetize16PlaytimeCampaign")
@interface PlaytimeCampaign : NSObject
/// App name.
@property (nonatomic, readonly, copy) NSString * _Nonnull appName;
/// Short description of the app.
@property (nonatomic, readonly, copy) NSString * _Nonnull appDescription;
/// Unique identifier for the app.
@property (nonatomic, readonly, copy) NSString * _Nonnull appID;
/// ID in the format <code>com.example.myapp</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable appBundleID;
/// Application’s store ID number that is part of the App Store link.
@property (nonatomic, readonly, copy) NSString * _Nullable appStoreID;
/// App installation timestamp (ISO 8601).
@property (nonatomic, readonly, copy) NSString * _Nullable installedAt;
/// App uninstallation timestamp (ISO 8601).
@property (nonatomic, readonly, copy) NSString * _Nullable uninstalledAt;
/// Expiration timestamp (ISO 8601) denoting how long players can get rewards after installing the app.
@property (nonatomic, readonly, copy) NSString * _Nullable rewardingExpiresAt;
/// Timestamp (ISO 8601) denoting the maximum amount of time after fetching the campaign that it can be installed.
@property (nonatomic, readonly, copy) NSString * _Nullable campaignExpiresAt;
/// Event and rewards configuration.
@property (nonatomic, readonly, strong) PlaytimeEventConfig * _Nullable eventConfig;
/// App category.
@property (nonatomic, readonly, copy) NSString * _Nullable appCategory;
/// Campaign type.
@property (nonatomic, readonly, copy) NSString * _Nullable campaignType;
/// Campaign media assets (portrait & landscape).
@property (nonatomic, readonly, strong) PlaytimeMedia * _Nullable image;
/// Campaign video media assets.
@property (nonatomic, readonly, strong) PlaytimeMedia * _Nullable video;
/// URL to the campaign icon image.
@property (nonatomic, readonly, copy) NSString * _Nullable iconImage;
/// Active promotion details, if any.
@property (nonatomic, readonly, strong) PlaytimePromotion * _Nullable promotion;
/// Flag indicating whether all rewards have been collected.
@property (nonatomic, readonly) BOOL isCompleted;
/// Campaign UUID.
@property (nonatomic, readonly, copy) NSString * _Nullable campaignUUID;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeCampaign (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@interface PlaytimeCampaign (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

/// The response of the SDK containing campaigns.
SWIFT_CLASS("_TtC16PlaytimeMonetize25PlaytimeCampaignsResponse")
@interface PlaytimeCampaignsResponse : NSObject
/// The requested selection of campaigns.
@property (nonatomic, readonly, copy) NSArray<PlaytimeCampaign *> * _Nonnull campaigns;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeCampaignsResponse (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@interface PlaytimeCampaignsResponse (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

/// Configuration for multi-event rewards.
/// The class provides detailed information about events and rewards.
SWIFT_CLASS("_TtC16PlaytimeMonetize19PlaytimeEventConfig")
@interface PlaytimeEventConfig : NSObject
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeEventConfig (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@interface PlaytimeEventConfig (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

/// This class is used to pass additional identifiers of the user.
SWIFT_CLASS("_TtC16PlaytimeMonetize18PlaytimeExtensions")
@interface PlaytimeExtensions : NSObject
/// An optional identifier that is provided back in the S2S payout URL.
@property (nonatomic, readonly, copy) NSString * _Nullable subId1;
/// An optional identifier that is provided back in the S2S payout URL.
@property (nonatomic, readonly, copy) NSString * _Nullable subId2;
/// An optional identifier that is provided back in the S2S payout URL.
@property (nonatomic, readonly, copy) NSString * _Nullable subId3;
/// An optional identifier that is provided back in the S2S payout URL.
@property (nonatomic, readonly, copy) NSString * _Nullable subId4;
/// An optional identifier that is provided back in the S2S payout URL.
@property (nonatomic, readonly, copy) NSString * _Nullable subId5;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeExtensions (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@interface PlaytimeExtensions (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

/// Use this builder to create an immutable instance of <code>PlaytimeExtensions</code>.
SWIFT_CLASS("_TtC16PlaytimeMonetize25PlaytimeExtensionsBuilder")
@interface PlaytimeExtensionsBuilder : NSObject
/// Set an optional identifier that is provided back in the S2S payout URL.
- (nonnull instancetype)setSubId1:(NSString * _Nullable)subId1 SWIFT_WARN_UNUSED_RESULT;
/// Set an optional identifier that is provided back in the S2S payout URL.
- (nonnull instancetype)setSubId2:(NSString * _Nullable)subId2 SWIFT_WARN_UNUSED_RESULT;
/// Set an optional identifier that is provided back in the S2S payout URL.
- (nonnull instancetype)setSubId3:(NSString * _Nullable)subId3 SWIFT_WARN_UNUSED_RESULT;
/// Set an optional identifier that is provided back in the S2S payout URL.
- (nonnull instancetype)setSubId4:(NSString * _Nullable)subId4 SWIFT_WARN_UNUSED_RESULT;
/// Set an optional identifier that is provided back in the S2S payout URL.
- (nonnull instancetype)setSubId5:(NSString * _Nullable)subId5 SWIFT_WARN_UNUSED_RESULT;
/// Build the extensions object that you pass to <code>PlaytimeOptions</code>.
- (PlaytimeExtensions * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The gender of the user.
typedef SWIFT_ENUM(NSInteger, PlaytimeGender, open) {
/// Male.
  PlaytimeGenderMale = 0,
/// Female.
  PlaytimeGenderFemale = 1,
/// Use this gender when you do not have this data about your user.
  PlaytimeGenderUnknown = 2,
};

/// A class representing a media item.
SWIFT_CLASS("_TtC16PlaytimeMonetize13PlaytimeMedia")
@interface PlaytimeMedia : NSObject
/// URL to portrait-oriented media.
@property (nonatomic, readonly, copy) NSString * _Nullable portrait;
/// URL to landscape-oriented media.
@property (nonatomic, readonly, copy) NSString * _Nullable landscape;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeMedia (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@interface PlaytimeMedia (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@class PlaytimeUserProfile;
@class PlaytimeParams;
/// The options passed to <code>Playtime</code> methods.
SWIFT_CLASS("_TtC16PlaytimeMonetize15PlaytimeOptions")
@interface PlaytimeOptions : NSObject
/// A custom identifier you must assign to each user.
@property (nonatomic, readonly, copy) NSString * _Nullable userId;
/// User profile for targeting.
@property (nonatomic, readonly, strong) PlaytimeUserProfile * _Nullable userProfile;
/// User acquisition parameters.
@property (nonatomic, readonly, strong) PlaytimeParams * _Nullable params;
/// Extension IDs visible in S2S payouts.
@property (nonatomic, readonly, strong) PlaytimeExtensions * _Nullable extensions;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeOptions (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@interface PlaytimeOptions (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

/// Use this builder to create an immutable instance of <code>PlaytimeOptions</code>.
SWIFT_CLASS("_TtC16PlaytimeMonetize22PlaytimeOptionsBuilder")
@interface PlaytimeOptionsBuilder : NSObject
/// Set a custom identifier you can assign to each user.
- (nonnull instancetype)setUserId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
/// Set user profile for targeting.
- (nonnull instancetype)setUserProfile:(PlaytimeUserProfile * _Nullable)userProfile SWIFT_WARN_UNUSED_RESULT;
/// Set user acquisition parameters.
- (nonnull instancetype)setParams:(PlaytimeParams * _Nullable)params SWIFT_WARN_UNUSED_RESULT;
/// Set extension IDs visible in S2S payouts.
- (nonnull instancetype)setExtensions:(PlaytimeExtensions * _Nullable)extensions SWIFT_WARN_UNUSED_RESULT;
/// Build the immutable <code>PlaytimeOptions</code> object.
- (PlaytimeOptions * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// The parameters related to User acquisition metadata.
SWIFT_CLASS("_TtC16PlaytimeMonetize14PlaytimeParams")
@interface PlaytimeParams : NSObject
/// User acquisition network where the user came from.
@property (nonatomic, readonly, copy) NSString * _Nullable uaNetwork;
/// User acquisition channel where the user came from; e.g. video, offerwall.
@property (nonatomic, readonly, copy) NSString * _Nullable uaChannel;
/// User acquisition sub ID in encrypted form where the user came from.
@property (nonatomic, readonly, copy) NSString * _Nullable uaSubPublisherEncrypted;
/// User acquisition sub ID in clear text where the user came from.
@property (nonatomic, readonly, copy) NSString * _Nullable uaSubPublisherCleartext;
/// The placement of the Playtime experience; e.g. “home screen”, “more options menu”.
@property (nonatomic, readonly, copy) NSString * _Nullable placement;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeParams (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@interface PlaytimeParams (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

/// Use this builder to create an immutable instance of <code>PlaytimeParam</code>.
SWIFT_CLASS("_TtC16PlaytimeMonetize21PlaytimeParamsBuilder")
@interface PlaytimeParamsBuilder : NSObject
/// Set user acquisition network where the user came from.
- (PlaytimeParamsBuilder * _Nonnull)setUANetwork:(NSString * _Nullable)uaNetwork SWIFT_WARN_UNUSED_RESULT;
/// Set user acquisition channel where the user came from; e.g. video, offerwall.
- (PlaytimeParamsBuilder * _Nonnull)setUAChannel:(NSString * _Nullable)uaChannel SWIFT_WARN_UNUSED_RESULT;
/// Set user acquisition sub ID in encrypted form where the user came from.
- (PlaytimeParamsBuilder * _Nonnull)setUASubPublisherEncrypted:(NSString * _Nullable)uaSubPublisherEncrypted SWIFT_WARN_UNUSED_RESULT;
/// Set user acquisition sub ID in clear text where the user came from.
- (PlaytimeParamsBuilder * _Nonnull)setUASubPublisherCleartext:(NSString * _Nullable)uaSubPublisherCleartext SWIFT_WARN_UNUSED_RESULT;
/// Set placement of the Playtime experience; e.g. “home screen”, “more options menu”.
- (PlaytimeParamsBuilder * _Nonnull)setPlacement:(NSString * _Nullable)placement SWIFT_WARN_UNUSED_RESULT;
/// Build immutable <code>PlaytimeParams</code>.
- (PlaytimeParams * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Permissions granted by the user.
SWIFT_CLASS("_TtC16PlaytimeMonetize19PlaytimePermissions")
@interface PlaytimePermissions : NSObject
/// Flag indicating whether the terms of service are accepted.
@property (nonatomic, readonly) BOOL isTOSAccepted;
/// Usage permissions. Not relevant on iOS.
@property (nonatomic, readonly) BOOL isUsagePermissionAccepted;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimePermissions (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@interface PlaytimePermissions (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

/// SDK response containing permissions.
SWIFT_CLASS("_TtC16PlaytimeMonetize27PlaytimePermissionsResponse")
@interface PlaytimePermissionsResponse : NSObject
/// Permissions granted by the user.
@property (nonatomic, readonly, strong) PlaytimePermissions * _Nonnull permissions;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimePermissionsResponse (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@interface PlaytimePermissionsResponse (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

/// Promotion representation.
SWIFT_CLASS("_TtC16PlaytimeMonetize17PlaytimePromotion")
@interface PlaytimePromotion : NSObject
/// Promotion name.
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// Description of the promotion.
@property (nonatomic, readonly, copy) NSString * _Nullable promotionDescription;
/// Promotion start timestamp (ISO 8601).
@property (nonatomic, readonly, copy) NSString * _Nullable startTime;
/// Promotion end timestamp (ISO 8601).
@property (nonatomic, readonly, copy) NSString * _Nullable endTime;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimePromotion (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@interface PlaytimePromotion (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

/// Rewarded action representation.
SWIFT_CLASS("_TtC16PlaytimeMonetize20PlaytimeRewardAction")
@interface PlaytimeRewardAction : NSObject
/// Reward action name.
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// Description of the task.
@property (nonatomic, readonly, copy) NSString * _Nullable taskDescription;
/// Type of task to complete.
/// Possible values: sequential, bonus, playtime.
@property (nonatomic, readonly, copy) NSString * _Nonnull taskType;
/// The amount of coins or rewards the user will receive upon completing the event.
@property (nonatomic, readonly) NSInteger amount;
/// Timestamp when a time-based reward was granted (ISO 8601).
@property (nonatomic, readonly, copy) NSString * _Nullable rewardedAt;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeRewardAction (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@interface PlaytimeRewardAction (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

/// The entry point of Adjoe Playtime SDK in Studio version.
/// This class provides methods to fetch campaigns and installed apps to show them in your custom UI.
/// note:
/// The SDK is functional starting from <em>iOS 14.0</em>.
SWIFT_CLASS("_TtC16PlaytimeMonetize14PlaytimeStudio")
@interface PlaytimeStudio : NSObject
/// Get the list of offers that a user can install.
+ (void)getCampaignsWithOptions:(PlaytimeOptions * _Nullable)options completionHandler:(void (^ _Nonnull)(PlaytimeCampaignsResponse * _Nullable, NSError * _Nullable))completionHandler;
/// Get a campaign by the specified token.
+ (void)getCampaignWithToken:(NSString * _Nonnull)token options:(PlaytimeOptions * _Nullable)options completionHandler:(void (^ _Nonnull)(PlaytimeCampaign * _Nullable, NSError * _Nullable))completionHandler;
/// Get the list of apps the user has already installed and that will contain the progress the user has made already.
+ (void)getInstalledCampaignsWithOptions:(PlaytimeOptions * _Nullable)options completionHandler:(void (^ _Nonnull)(PlaytimeCampaignsResponse * _Nullable, NSError * _Nullable))completionHandler;
/// Use this method to forward the user to the store.
+ (void)openInStoreWithCampaign:(PlaytimeCampaign * _Nonnull)campaign completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Get user’s permissions.
+ (void)getPermissionsWithCompletionHandler:(void (^ _Nonnull)(PlaytimePermissionsResponse * _Nullable, NSError * _Nullable))completionHandler;
/// Show the prompt requesting user’s permissions.
+ (void)showPermissionsPromptWithCompletionHandler:(void (^ _Nonnull)(PlaytimePermissionsResponse * _Nullable, NSError * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Additional user information.
SWIFT_CLASS("_TtC16PlaytimeMonetize19PlaytimeUserProfile")
@interface PlaytimeUserProfile : NSObject
/// User gender. Valid options are <code>male</code>, <code>female</code>, <code>unknown</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable gender;
/// ISO8601 timestamp designating user’s birthday, e.g. <code>2025-06-26T14:45:30.123Z</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable birthday;
/// :nodoc:
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PlaytimeUserProfile (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This method exists for wrapper compatibility. It is not recommended that you use it directly.
- (NSDictionary<NSString *, id> * _Nonnull)toJSONObject SWIFT_WARN_UNUSED_RESULT;
@end

@interface PlaytimeUserProfile (SWIFT_EXTENSION(PlaytimeMonetize))
/// :nodoc:
/// warning:
/// This initializer exists for wrapper compatibility. It is not recommended that you use it directly.
- (nullable instancetype)initWithJSONObject:(id _Nonnull)JSONObject error:(NSError * _Nullable * _Nullable)error;
@end

@class NSDate;
/// Use this builder to create an immutable instance of <code>PlaytimeUserProfile</code>.
SWIFT_CLASS("_TtC16PlaytimeMonetize26PlaytimeUserProfileBuilder")
@interface PlaytimeUserProfileBuilder : NSObject
/// Set user’s gender.
- (nonnull instancetype)setGender:(enum PlaytimeGender)gender SWIFT_WARN_UNUSED_RESULT;
/// Set user’s birthday.
- (nonnull instancetype)setBirthday:(NSDate * _Nullable)birthday SWIFT_WARN_UNUSED_RESULT;
/// Build immutable <code>PlaytimeUserProfile</code>.
- (PlaytimeUserProfile * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
